### PR TITLE
Bump flyway version to 7.0.4

### PR DESCRIPTION
**Pull request by dekstroza**
Upgrade flyway to version 7.0.4
Ignore jdbcProperties during configuration, since its available only in commercial version of flyway.

### CODE REVIEW

**Comment by ilopmar** [comment]
@dekstroza why have you removed `ScannerSubstitutions.java`? Have you checked the without it Flyway still works with GraalVM?

**Comment by ilopmar** [comment]
Thank, I'll take a look.

I wouldn't worry too much about static compilation, it's not fully supported yet in GraalVM and have some issues (especially with Java 8).

**Comment by dekstroza** [comment]
> Thank, I'll take a look.
> 
> I wouldn't worry too much about static compilation, it's not fully supported yet in GraalVM and have some issues (especially with Java 8).

Thanks, let me know if something else needs update. Static linking actually works surprisingly well for me on both 8 and 11, for most of the micronaut components. It’s a very important feature for me(so I do test with it) and we have worked with Oracle some time ago to get it running on the other project.

**Comment by ilopmar** [comment]
I have been testing this and it doesn't work for me. A few comments:

- The class you removed is necessary but it is failing because a change in Flyway. See #110
- Besides the methods you've added to the substitutions, I've also added `isLog4J2Available`


With these changes your test application is not working for me, it doesn't find any db migration:

```
13:33:50.621 [main] INFO  i.m.flyway.AbstractFlywayMigration - Running migrations for database with qualifier [default]
13:33:50.621 [main] INFO  o.f.c.i.license.VersionPrinter - Flyway Community Edition 7.0.4 by Redgate
13:33:50.621 [main] ERROR o.f.c.i.s.classpath.ClassPathScanner - Unable to resolve location classpath:db/migration.
13:33:50.731 [main] INFO  o.f.c.i.database.base.DatabaseType - Database: jdbc:postgresql://localhost:5432/users (PostgreSQL 11.5)
13:33:50.740 [main] INFO  o.f.core.internal.command.DbValidate - Successfully validated 0 migrations (execution time 00:00.005s)
13:33:50.740 [main] WARN  o.f.core.internal.command.DbValidate - No migrations found. Are your locations set up correctly?
13:33:50.745 [main] INFO  o.f.c.i.s.JdbcTableSchemaHistory - Creating Schema History table "public"."flyway_schema_history" ...
13:33:50.762 [main] INFO  o.f.core.internal.command.DbMigrate - Current version of schema "public": << Empty Schema >>
13:33:50.762 [main] INFO  o.f.core.internal.command.DbMigrate - Schema "public" is up to date. No migration necessary.
13:33:50.763 [main] INFO  org.hibernate.Version - HHH000412: Hibernate ORM core version [WORKING]
13:33:50.765 [main] INFO  o.h.annotations.common.Version - HCANN000001: Hibernate Commons Annotations {5.1.0.Final}
13:33:50.766 [main] INFO  org.hibernate.dialect.Dialect - HHH000400: Using dialect: org.hibernate.dialect.PostgreSQL10Dialect
13:33:50.819 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 222ms. Server Running: http://localhost:8080
```

Restoring the removed class and fixing the method signature makes the migration on my test application fail with:

```
12:56:23.102 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
12:56:23.127 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
12:56:23.130 [main] DEBUG o.f.c.i.s.classpath.ClassPathScanner - Scanning for classpath resources at 'classpath:db/callback' ...
12:56:23.130 [main] DEBUG o.f.c.i.s.classpath.ClassPathScanner - Determining location urls for classpath:db/callback using ClassLoader sun.misc.Launcher$AppClassLoader@7f9fe01593c0 ...
12:56:23.130 [main] DEBUG o.f.c.i.s.classpath.ClassPathScanner - Unable to resolve location classpath:db/callback.
12:56:23.130 [main] INFO  i.m.flyway.AbstractFlywayMigration - Running migrations for database with qualifier [default]
12:56:23.130 [main] INFO  o.f.c.i.license.VersionPrinter - Flyway Community Edition 7.0.4 by Redgate
12:56:23.133 [main] INFO  o.f.c.i.database.base.DatabaseType - Database: jdbc:postgresql://localhost:5432/users (PostgreSQL 11.5)
12:56:23.133 [main] DEBUG o.f.c.i.database.base.DatabaseType - Driver  : PostgreSQL JDBC Driver 42.2.16
12:56:23.133 [main] DEBUG org.flywaydb.core.Flyway - DDL Transactions Supported: true
12:56:23.133 [main] DEBUG org.flywaydb.core.Flyway - Schemas: 
12:56:23.133 [main] DEBUG org.flywaydb.core.Flyway - Default schema: null
12:56:23.139 [main] DEBUG o.f.c.i.c.SqlScriptCallbackFactory - Scanning for SQL callbacks ...
12:56:23.145 [main] DEBUG o.f.core.internal.command.DbValidate - Validating migrations ...
12:56:23.146 [main] DEBUG o.f.c.i.j.TransactionalExecutionTemplate - Rolling back transaction...
12:56:23.146 [main] DEBUG o.f.c.i.j.TransactionalExecutionTemplate - Transaction rolled back
12:56:23.149 [main] DEBUG org.flywaydb.core.Flyway - Memory usage: 8 of 25586M
12:56:23.149 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [javax.sql.DataSource] could not be loaded: null
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [javax.sql.DataSource] could not be loaded: null
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1549)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:220)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2780)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:233)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:166)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:64)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:299)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:285)
	at micronaut.example.Application.main(Application.java:8)
Caused by: java.lang.NullPointerException: null
	at org.flywaydb.core.internal.scanner.Scanner.getResource(Scanner.java:112)
	at org.flywaydb.core.internal.sqlscript.SqlScriptMetadata.getMetadataResource(SqlScriptMetadata.java:65)
	at org.flywaydb.core.internal.database.base.DatabaseType$1.createSqlScript(DatabaseType.java:200)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationResolver.addMigrations(SqlMigrationResolver.java:169)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationResolver.resolveMigrations(SqlMigrationResolver.java:88)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationResolver.resolveMigrations(SqlMigrationResolver.java:44)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.collectMigrations(CompositeMigrationResolver.java:132)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.doFindAvailableMigrations(CompositeMigrationResolver.java:114)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:100)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:47)
	at org.flywaydb.core.internal.info.MigrationInfoServiceImpl.refresh(MigrationInfoServiceImpl.java:149)
	at org.flywaydb.core.internal.command.DbValidate$2.call(DbValidate.java:160)
	at org.flywaydb.core.internal.command.DbValidate$2.call(DbValidate.java:147)
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66)
	at org.flywaydb.core.internal.command.DbValidate.validate(DbValidate.java:147)
	at org.flywaydb.core.Flyway.doValidate(Flyway.java:316)
	at org.flywaydb.core.Flyway.access$100(Flyway.java:75)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:168)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:163)
	at org.flywaydb.core.Flyway.execute(Flyway.java:532)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:163)
	at io.micronaut.flyway.AbstractFlywayMigration.runFlyway(AbstractFlywayMigration.java:90)
	at io.micronaut.flyway.AbstractFlywayMigration.run(AbstractFlywayMigration.java:74)
	at io.micronaut.flyway.DataSourceMigrationRunner.lambda$null$0(DataSourceMigrationRunner.java:65)
	at java.util.Optional.ifPresent(Optional.java:159)
	at io.micronaut.flyway.DataSourceMigrationRunner.lambda$onCreated$1(DataSourceMigrationRunner.java:63)
	at java.util.Optional.ifPresent(Optional.java:159)
	at io.micronaut.flyway.DataSourceMigrationRunner.onCreated(DataSourceMigrationRunner.java:60)
	at io.micronaut.flyway.DataSourceMigrationRunner.onCreated(DataSourceMigrationRunner.java:37)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1954)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2647)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2633)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2172)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1543)
	... 8 common frames omitted

```

Which is the same issue previously reported in #110.

I'll dig a little bit more into this.

**Comment by dekstroza** [comment]
I will check again now. Am fairly sure it was working fine. Do you want me to update pull request with substitution you added?

**Comment by dekstroza** [comment]
I just ran it with build from my pull request, and in the project tests pass:
```
[INFO]
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ postgresnaut ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.dekstroza.AlarmsControllerTest
12:48:40.470 [main] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [test]
12:48:42.137 [main] INFO  i.m.flyway.AbstractFlywayMigration - Running migrations for database with qualifier [default]
12:48:42.140 [main] INFO  o.f.c.i.license.VersionPrinter - Flyway Community Edition 7.0.4 by Redgate
12:48:42.246 [main] INFO  o.t.d.DockerClientProviderStrategy - Loaded org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy
 from ~/.testcontainers.properties, will try it first
12:48:43.058 [main] INFO  o.t.d.DockerClientProviderStrategy - Found Docker environment with Environment variables, system properties and defaults. Reso
lved dockerHost=tcp://127.0.0.1:2375
12:48:43.058 [main] INFO  o.testcontainers.DockerClientFactory - Docker host IP address is 127.0.0.1
12:48:43.104 [main] INFO  o.testcontainers.DockerClientFactory - Connected to docker:
  Server Version: 19.03.13
  API Version: 1.40
  Operating System: Docker Desktop
  Total Memory: 15995 MB
12:48:43.811 [main] INFO  o.testcontainers.DockerClientFactory - Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
12:48:43.811 [main] INFO  o.testcontainers.DockerClientFactory - Checking the system...
12:48:43.812 [main] INFO  o.testcontainers.DockerClientFactory - ✔︎ Docker server version should be at least 1.6.0
12:48:43.936 [main] INFO  o.testcontainers.DockerClientFactory - ✔︎ Docker environment should have more than 2GB free disk space
12:48:44.030 [main] INFO  � [postgres:12] - Creating container for image: postgres:12
12:48:44.109 [main] INFO  � [postgres:12] - Starting container with ID: e05deba5c088c9208276f6484eb0acb445da3ab294c48d75c9758d0fc540e6ce
12:48:44.395 [main] INFO  � [postgres:12] - Container postgres:12 is starting: e05deba5c088c9208276f6484eb0acb445da3ab294c48d75c9758d0fc540e6ce
12:48:45.683 [main] INFO  � [postgres:12] - Container postgres:12 started in PT3.452216S
12:48:46.095 [main] INFO  o.f.c.i.database.base.DatabaseType - Database: jdbc:postgresql://127.0.0.1:32835/test (PostgreSQL 12.4)
12:48:46.184 [main] INFO  o.f.core.internal.command.DbValidate - Successfully validated 2 migrations (execution time 00:00.042s)
12:48:46.210 [main] INFO  o.f.c.i.s.JdbcTableSchemaHistory - Creating Schema History table "public"."flyway_schema_history" ...
12:48:46.270 [main] INFO  o.f.core.internal.command.DbMigrate - Current version of schema "public": << Empty Schema >>
12:48:46.281 [main] INFO  o.f.core.internal.command.DbMigrate - Migrating schema "public" to version "1 - create-alarms-db-schema"
12:48:46.327 [main] INFO  o.f.core.internal.command.DbMigrate - Migrating schema "public" to version "2 - create-alarms-db-schema"
12:48:46.345 [main] WARN  o.f.c.i.s.DefaultSqlScriptExecutor - DB: relation "alarms" already exists, skipping (SQL State: 42P07 - Error Code: 0)
12:48:46.380 [main] INFO  o.f.core.internal.command.DbMigrate - Successfully applied 2 migrations to schema "public" (execution time 00:00.128s)
12:48:46.418 [main] INFO  org.hibernate.Version - HHH000412: Hibernate ORM core version 5.4.21.Final
12:48:46.689 [main] INFO  o.h.annotations.common.Version - HCANN000001: Hibernate Commons Annotations {5.1.0.Final}
12:48:46.897 [main] INFO  org.hibernate.dialect.Dialect - HHH000400: Using dialect: org.hibernate.dialect.PostgreSQL10Dialect
Hibernate: select alarm0_.id as id1_0_, alarm0_.name as name2_0_, alarm0_.severity as severity3_0_ from alarms alarm0_
Hibernate: select alarm0_.id as id1_0_, alarm0_.name as name2_0_, alarm0_.severity as severity3_0_ from alarms alarm0_ where alarm0_.id=? limit ?
Hibernate: select alarm0_.id as id1_0_, alarm0_.name as name2_0_, alarm0_.severity as severity3_0_ from alarms alarm0_ where alarm0_.severity=?
Hibernate: select nextval ('alarms_id_seq')
Hibernate: insert into alarms (name, severity, id) values (?, ?, ?)
Hibernate: select alarm0_.id as id1_0_, alarm0_.name as name2_0_, alarm0_.severity as severity3_0_ from alarms alarm0_ where alarm0_.severity=?
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 10.869 s - in io.dekstroza.AlarmsControllerTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0
```
but you are right once compiled with the graalvm its not finding migrations, I ve missed that part somehow in the logs:
```
➜  postgresnaut git:(master) ✗ kubectl logs desa-postgresnaut-67584844df-5l9k2 postgresnaut
12:54:49.698 [main] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [k8s, cloud]
12:54:49.721 [main] INFO  i.m.flyway.AbstractFlywayMigration - Running migrations for database with qualifier [default]
12:54:49.721 [main] INFO  o.f.c.i.license.VersionPrinter - Flyway Community Edition 7.0.4 by Redgate
12:54:49.721 [main] ERROR o.f.c.i.s.classpath.ClassPathScanner - Unable to resolve location classpath:db/migration.
12:54:49.793 [main] INFO  o.f.c.i.database.base.DatabaseType - Database: jdbc:postgresql://desa-postgresql:5432/postgresnaut (PostgreSQL 11.9)
12:54:49.802 [main] INFO  o.f.core.internal.command.DbValidate - Successfully validated 0 migrations (execution time 00:00.005s)
12:54:49.803 [main] WARN  o.f.core.internal.command.DbValidate - No migrations found. Are your locations set up correctly?
12:54:49.808 [main] INFO  o.f.c.i.s.JdbcTableSchemaHistory - Creating Schema History table "public"."flyway_schema_history" ...
12:54:49.833 [main] INFO  o.f.core.internal.command.DbMigrate - Current version of schema "public": << Empty Schema >>
12:54:49.833 [main] INFO  o.f.core.internal.command.DbMigrate - Schema "public" is up to date. No migration necessary.
12:54:49.834 [main] INFO  org.hibernate.Version - HHH000412: Hibernate ORM core version [WORKING]
12:54:49.835 [main] INFO  o.h.annotations.common.Version - HCANN000001: Hibernate Commons Annotations {5.1.0.Final}
12:54:49.836 [main] INFO  org.hibernate.dialect.Dialect - HHH000400: Using dialect: org.hibernate.dialect.PostgreSQL10Dialect
12:54:49.870 [main] DEBUG io.jaegertracing.Configuration - Found a Metrics Factory service: class io.jaegertracing.micrometer.MicrometerMetricsFactory
12:54:49.870 [main] DEBUG i.j.t.i.senders.ThriftSenderFactory - Using the UDP Sender to send spans to the agent.
12:54:49.870 [main] DEBUG i.j.internal.senders.SenderResolver - Using sender UdpSender()
12:54:49.902 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 246ms. Server Running: http://desa-postgresnaut-67584844df-5l9k2:8080
➜  postgresnaut git:(master) ✗
```
I 'll have another look, to see if i can figure out why its not finding migrations. Sorry about this, I missed the lined in the log completely.

**Comment by ilopmar** [comment]
Yeah, I also needed to add `flyway-core:7.0.4` dependency.

**Comment by ilopmar** [comment]
@dekstroza I've fixed the issue with 6.5.5 (#110). The same fix also works for 7.0.4, I only need to add the three new extra methods in `FeatureDetectorSubstitutions` and modify the constructor.

I'll cleanup my code and I'll release a new version Micronaut-Flyway with Flyway 6.5.7 support and another one with 7.0.4 support, so I'm closing this issue.

Thanks for your help :)

**Comment by ilopmar** [comment]
Sure, I'll include the hints!

**Pull request closed without merging**
